on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old test Docker images
    steps:
      - uses: snok/container-retention-policy@v3.1.0
        with:
          account: deanrock
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "speedtest-exporter"
          image-tags: "sha-*"
          cut-off: 1w
          dry-run: true
